### ISSUE TITLE
Add pt-br.js

### ISSUE THREAD

**Issue by OtacilioN** [wooorm/retext-profanities#12]
Hey folks, 

I will start the intenationalisation to Portuguese From Brazil, so I will create a file called pt-br.js 

Should I wrap this file in a internationalisation folder? resulting in translations/pt-br.js ? Or just leave in the root of the repository? 

Best Regards,
Otacilio Maia.

**Comment by OtacilioN** [comment]
Hey folks, I did not get where this is used. 

/* List of values not to normalize. */
var APOSTROPHES = ["hell"];

**Comment by wooorm** [comment]
@OtacilioN Hey! Thanks for working on this!

* So, have you found out that that you can use [`cuss/pt-br.js`](https://github.com/words/cuss) for the translations?
* Yes, I suggest creating a file `pt-br.js` that calls some sort of factory that creates the plugin. Then `index.js` will do something similar but with the English cuss map. Feel free to place it in the root
* The `var APOSTROPHES = ["hell"];` part is because, by default, apostrophes are ignored, so `he’ll` (short for he will) would be seen as `hell`, which is something different. That list there means that `in the case of `hell`, it should not search for values with apostrophes. I think you probably don’t need to worry about this with Portuguese, only English does (for now)
